spring:
  application:
    name: mcp-client
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  ai:
    openai:
      api-key: sk-4410a74452d245ddbcfac50318840b79
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
    mcp:
      client:
        type: SYNC
        request-timeout: 30s
        toolcallback:
          enabled: true
        sse:
          connections:
            mcp-server:
              url: http://localhost:8080
server:
  port: 9090